name: flutter_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  # State Management
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Screen responsive
  responsive_framework: ^1.4.0

  # Splash screen
  flutter_native_splash: ^2.4.1

  # Navigation
  go_router: ^14.2.0

  easy_localization: ^3.0.1

  json_annotation: ^4.8.0
  uuid: ^4.4.0

  # For getting device info
  package_info_plus: ^8.0.0

  # For Networking
  dio: ^5.0.0
  retrofit: ">=4.0.0 <5.0.0"
  pretty_dio_logger: ^1.3.1
  logger: any

  # Lightweight, secure local storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.2
  flutter_gen: ^5.6.0

  # Widgets
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter
  test: ^1.25.2

  flutter_gen_runner:
  flutter_dotenv: ^5.0.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  riverpod_generator: ^2.4.2
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12

  # For Networking
  retrofit_generator: ^8.1.0

  # Json serializable & data class model
  enum_to_string: ^2.0.1

  # Platform information
  package_info: ^2.0.2

  # Support for design
  flutter_svg: ^2.0.0+1
  flutter_lints: ^4.0.0

dependency_overrides:
  meta: ^1.15.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/ic_splash.png
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/ic_splash_android_12.png

flutter_gen:
  output: lib/generated # Optional (default: lib/gen/)
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true

    outputs:
      # Available values:
      # style: camel-case # Assets.imagesChip
      # style: snake-case # Assets.images_chip
      # style: dot-delimiter # Assets.images.chip (default style)
      style: dot-delimiter
      # class_name: ResAssets # Optional (default: Assets)
      exclude:
        - assets/translations/

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    # env
    - assets/.env.develop
    - assets/.env.production
    - assets/.env.staging
    - assets/translations/

    # source
    - assets/images/
    - assets/videos/
    - assets/json/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 900
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/Muli-Italic.ttf
          style: italic
